-- Insert sample car sale records
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (1, 30);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (2, 29);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (3, 28);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (4, 27);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (5, 26);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (6, 25);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (7, 1);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (8, 2);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (9, 2);
INSERT INTO CAR_SALE_INFO (Invoice_ID, Car_ID) VALUES (5, 4);

COMMIT;
