-- 1. CAR_BODY_TYPE
CREATE TABLE CAR_BODY_TYPE
(
 Body_ID              NUMBER(10) NOT NULL,
 Type_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_CAR_BODY_TYPE PRIMARY KEY (Body_ID)
);

-- 2. CAR_MANUFACTURER
CREATE TABLE CAR_MANUFACTURER
(
 Manufacturer_ID              NUMBER(10) NOT NULL,
 Manufacturer_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_CAR_MANUFACTURER PRIMARY KEY (Manufacturer_ID)
);


-- 3. FUEL_TYPE
CREATE TABLE FUEL_TYPE
(
 Fuel_Type_ID              NUMBER(10) NOT NULL,
 Fuel_Type_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_FUEL_TYPE PRIMARY KEY (Fuel_Type_ID)
);

-- 4. ENGINE_TYPE
CREATE TABLE ENGINE_TYPE
(
 Engine_ID              NUMBER(10) NOT NULL,
 Engine_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_ENGINE_TYPE PRIMARY KEY (Engine_ID)
);

-- 5. COLOUR_TYPE
CREATE TABLE COLOUR_TYPE
(
 Colour_ID       NUMBER(10) NOT NULL,
 Colour_Name     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_COLOUR_TYPE PRIMARY KEY (Colour_ID)
);

-- 6. DRIVE_TYPE
CREATE TABLE DRIVE_TYPE
(
 Drive_Type_ID              NUMBER(10) NOT NULL,
 Drive_Type_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_DRIVE_TYPE PRIMARY KEY (Drive_Type_ID)
);

-- 7. CONDITION
CREATE TABLE CONDITION
(
 Condition_ID              NUMBER(10) NOT NULL,
 Condition_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_CONDITION PRIMARY KEY (Condition_ID)
);


-- 8. TRANSMISSION_TYPE
CREATE TABLE TRANSMISSION_TYPE
(
 Transmission_Type_ID              NUMBER(10) NOT NULL,
 Transmission_Type_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_TRANSMISSION_TYPE PRIMARY KEY (Transmission_Type_ID)
);

-- 9. CAR
CREATE TABLE CAR
(
 Car_ID                   NUMBER(10) NOT NULL,
 Body_Type_ID             NUMBER(10) NOT NULL,
 Manufacturer_ID          NUMBER(10) NOT NULL,
 Fuel_Type_ID             NUMBER(10) NOT NULL,
 Engine_ID                NUMBER(10) NOT NULL,
 Colour_ID                NUMBER(10) NOT NULL,
 Drive_Type_ID            NUMBER(10) NOT NULL,
 Condition_ID             NUMBER(10) NOT NULL,
 Transmission_Type_ID     NUMBER(10) NOT NULL,
 Price                    NUMBER(10, 2) NOT NULL,
 Mileage                  NUMBER(7) NOT NULL,
 C_Year                   NUMBER(4) NOT NULL,
 CONSTRAINT PK_CAR PRIMARY KEY (Car_ID),
 CONSTRAINT FK_CAR_1 FOREIGN KEY (Body_Type_ID) REFERENCES CAR_BODY_TYPE (Body_ID),
 CONSTRAINT FK_CAR_2 FOREIGN KEY (Manufacturer_ID) REFERENCES CAR_MANUFACTURER (Manufacturer_ID),
 CONSTRAINT FK_CAR_3 FOREIGN KEY (Fuel_Type_ID) REFERENCES FUEL_TYPE (Fuel_Type_ID),
 CONSTRAINT FK_CAR_4 FOREIGN KEY (Engine_ID) REFERENCES ENGINE_TYPE (Engine_ID),
 CONSTRAINT FK_CAR_5 FOREIGN KEY (Colour_ID) REFERENCES COLOUR_TYPE (Colour_ID),
 CONSTRAINT FK_CAR_6 FOREIGN KEY (Drive_Type_ID) REFERENCES DRIVE_TYPE (Drive_Type_ID),
 CONSTRAINT FK_CAR_7 FOREIGN KEY (Condition_ID) REFERENCES CONDITION (Condition_ID),
 CONSTRAINT FK_CAR_8 FOREIGN KEY (Transmission_Type_ID) REFERENCES TRANSMISSION_TYPE (Transmission_Type_ID)
);

-- 11. DEPARTMENT
CREATE TABLE DEPARTMENT
(
 Department_ID       NUMBER(10) NOT NULL,
 Department_Name     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Department_ID)
);

-- 12. EMPLOYEE
CREATE TABLE EMPLOYEE
(
 Employee_ID       NUMBER(10) NOT NULL,
 RSA_ID            NUMBER(10) NOT NULL,
 Emp_Name          VARCHAR2(80) NOT NULL,
 Surname           VARCHAR2(80) NOT NULL,
 Cellphone         VARCHAR2(80) NOT NULL,
 Email             VARCHAR2(80) NOT NULL,
 Department_ID     NUMBER(10) NOT NULL,
 CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Employee_ID),
 CONSTRAINT FK_EMPLOYEE_1 FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT (Department_ID)
);

-- 13. CUSTOMER
CREATE TABLE CUSTOMER
(
 Customer_ID     NUMBER(10) NOT NULL,
 FName           VARCHAR2(80) NOT NULL,
 Surname         VARCHAR2(80) NOT NULL,
 Cellphone       VARCHAR2(80) NOT NULL,
 Email           VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_CUSTOMER PRIMARY KEY (Customer_ID)
);

-- 14. PART_CATEGORY
CREATE TABLE PART_CATEGORY
(
 Category_ID              NUMBER(10) NOT NULL,
 Category_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_PART_CATEGORY PRIMARY KEY (Category_ID)
);


-- 15. PART_MANUFACTURER
CREATE TABLE PART_MANUFACTURER
(
 Manufacturer_ID              NUMBER(10) NOT NULL,
 Manufacturer_Description     VARCHAR2(80) NOT NULL,
 CONSTRAINT PK_PART_MANUFACTURER PRIMARY KEY (Manufacturer_ID)
);

-- 16. PART
CREATE TABLE PART
(
 Part_ID             NUMBER(10) NOT NULL,
 Manufacturer_ID     NUMBER(10) NOT NULL,
 Category_ID         NUMBER(10) NOT NULL,
 Price               NUMBER(10, 2) NOT NULL,
 CONSTRAINT PK_PART PRIMARY KEY (Part_ID),
 CONSTRAINT FK_PART_1 FOREIGN KEY (Manufacturer_ID) REFERENCES PART_MANUFACTURER (Manufacturer_ID),
 CONSTRAINT FK_PART_2 FOREIGN KEY (Category_ID) REFERENCES PART_CATEGORY (Category_ID)
); 

-- 10. SALES
CREATE TABLE SALES
(
 Invoice_ID      NUMBER(10) NOT NULL,
 Employee_ID     NUMBER(10) NOT NULL,
 Customer_ID     NUMBER(10) NOT NULL,
 Sales_Date      DATE NOT NULL,
 CONSTRAINT PK_SALES PRIMARY KEY (Invoice_ID),
 CONSTRAINT FK_SALES_1 FOREIGN KEY (Employee_ID) REFERENCES EMPLOYEE (Employee_ID),
 CONSTRAINT FK_SALES_2 FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER (Customer_ID)
);

-- 17. PART_SALE_INFO  (joins PART ? SALES)
CREATE TABLE PART_SALE_INFO
(
 Invoice_ID     NUMBER(10) NOT NULL,
 Part_ID        NUMBER(10) NOT NULL,
 Quantity       NUMBER(10) NOT NULL,
 CONSTRAINT PK_PART_SALE_INFO PRIMARY KEY (Invoice_ID, Part_ID),
 CONSTRAINT FK_PART_SALE_INFO_1 FOREIGN KEY (Invoice_ID) REFERENCES SALES (Invoice_ID),
 CONSTRAINT FK_PART_SALE_INFO_2 FOREIGN KEY (Part_ID) REFERENCES PART (Part_ID)
);

-- 18. CAR_SALE_INFO   (joins CAR ? SALES)
CREATE TABLE CAR_SALE_INFO
(
 Invoice_ID     NUMBER(10) NOT NULL,
 Car_ID         NUMBER(10) NOT NULL,
 CONSTRAINT PK_CAR_SALE_INFO PRIMARY KEY (Invoice_ID, Car_ID),
 CONSTRAINT FK_CAR_SALE_INFO_1 FOREIGN KEY (Invoice_ID) REFERENCES SALES (Invoice_ID),
 CONSTRAINT FK_CAR_SALE_INFO_2 FOREIGN KEY (Car_ID) REFERENCES CAR (Car_ID)
);

